/**
 * @file command.hpp
 * @brief Graph mutation commands: the single expression of **every** structural change.
 *
 * ## Why an explicit command type instead of exposing Graph's mutators directly
 *
 * Three reasons, each sufficient on its own:
 *
 * 1. **Undo/redo needs storable operations**. After `Graph::connect()` returns nothing remains;
 *    a `Command` value can go on the undo stack, be serialized, be sent to another view.
 *
 * 2. **Multiple views must share one editing channel**. If the node editor, the YAML view and
 *    the block view each mutate `Graph` directly, nothing can validate, invalidate or undo
 *    uniformly. Commands are that channel.
 *
 * 3. **A command is checkable, previewable, recordable data**. Those three let "may I do this"
 *    and "what will the graph look like afterwards" be answered **without really mutating it**.
 *
 * ## A command is a value, not a callback
 *
 * A command holds no function pointer, no closure, no `this`. It is pure data, so it can
 * be compared, printed, stored in a file. Callback-style commands cannot do that, and they
 * would drag lifetime problems into the undo stack.
 *
 * @ownership   pure (value type)
 * @thread      any (read-only after construction)
 * @pre         none
 * @post        none
 * @invariant   a command itself holds no reference to any graph
 * @errors      noexcept
 * @frozen      no (extensible; the semantics of existing variants are frozen)
 */
#pragma once

#include <qp/graph/ir.hpp>
#include <qp/ports/value.hpp>

#include <algorithm>
#include <cstdint>
#include <optional>
#include <string>
#include <variant>
#include <vector>

namespace qp::graph {

/// @brief The complete initial state of a node when created. Restores it exactly on undo.
struct NodeSnapshot final {
    NodeId id{};
    std::string type_name;
    std::string name;
    std::vector<ParamValue> params;
    bool bypassed = false;

    [[nodiscard]] friend bool operator==(const NodeSnapshot& a,
                                         const NodeSnapshot& b) noexcept {
        return a.id == b.id && a.type_name == b.type_name && a.name == b.name &&
               a.bypassed == b.bypassed && a.params.size() == b.params.size() &&
               std::equal(a.params.begin(), a.params.end(), b.params.begin(),
                          [](const ParamValue& x, const ParamValue& y) {
                              return x.number == y.number && x.value == y.value;
                          });
    }
};

/// @brief The complete record of one edge. Restores it exactly when undoing a disconnect.
struct EdgeSnapshot final {
    PortRef from{};
    PortRef to{};

    [[nodiscard]] friend constexpr bool operator==(EdgeSnapshot a, EdgeSnapshot b) noexcept {
        return a.from == b.from && a.to == b.to;
    }
};

/// @brief Add a node.
struct AddNode final {
    /// Supplied by the caller (usually from `CommandBus::reserve_node()`).
    /// **Not** generated by the command: this keeps the id stable across undo and redo.
    NodeId id{};
    std::string type_name;
    std::string name;

    [[nodiscard]] friend bool operator==(const AddNode& a, const AddNode& b) noexcept {
        return a.id == b.id && a.type_name == b.type_name && a.name == b.name;
    }
};

/// @brief Delete a node (together with all of its edges).
struct RemoveNode final {
    NodeId id{};

    [[nodiscard]] friend constexpr bool operator==(RemoveNode a, RemoveNode b) noexcept {
        return a.id == b.id;
    }
};

/// @brief Set a node parameter.
struct SetParam final {
    NodeId id{};
    PortNumber port = 0;
    qp::ports::Value value{};

    [[nodiscard]] friend bool operator==(const SetParam& a, const SetParam& b) noexcept {
        return a.id == b.id && a.port == b.port && a.value == b.value;
    }
};

/// @brief Erase a node parameter (back to "not set").
struct EraseParam final {
    NodeId id{};
    PortNumber port = 0;

    [[nodiscard]] friend constexpr bool operator==(EraseParam a, EraseParam b) noexcept {
        return a.id == b.id && a.port == b.port;
    }
};

/// @brief Set a node's user name.
struct SetNodeName final {
    NodeId id{};
    std::string name;

    [[nodiscard]] friend bool operator==(const SetNodeName& a,
                                         const SetNodeName& b) noexcept {
        return a.id == b.id && a.name == b.name;
    }
};

/// @brief Set a node's bypass flag.
struct SetBypass final {
    NodeId id{};
    bool bypassed = false;

    [[nodiscard]] friend constexpr bool operator==(SetBypass a, SetBypass b) noexcept {
        return a.id == b.id && a.bypassed == b.bypassed;
    }
};

/// @brief Make a connection.
struct Connect final {
    PortRef from{};
    PortRef to{};

    [[nodiscard]] friend constexpr bool operator==(Connect a, Connect b) noexcept {
        return a.from == b.from && a.to == b.to;
    }
};

/// @brief Disconnect whatever edge feeds one input port.
struct Disconnect final {
    PortRef input{};

    [[nodiscard]] friend constexpr bool operator==(Disconnect a, Disconnect b) noexcept {
        return a.input == b.input;
    }
};

/// @brief All command variants. A new operation must be registered here -- the only entry point.
using Command = std::variant<AddNode, RemoveNode, SetParam, EraseParam, SetNodeName, SetBypass,
                             Connect, Disconnect>;

/// @brief Stable short name of a command. Used in logs, the undo stack and test assertions.
[[nodiscard]] inline const char* command_name(const Command& c) noexcept {
    return std::visit(
        [](const auto& v) -> const char* {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, AddNode>) return "AddNode";
            else if constexpr (std::is_same_v<T, RemoveNode>) return "RemoveNode";
            else if constexpr (std::is_same_v<T, SetParam>) return "SetParam";
            else if constexpr (std::is_same_v<T, EraseParam>) return "EraseParam";
            else if constexpr (std::is_same_v<T, SetNodeName>) return "SetNodeName";
            else if constexpr (std::is_same_v<T, SetBypass>) return "SetBypass";
            else if constexpr (std::is_same_v<T, Connect>) return "Connect";
            else if constexpr (std::is_same_v<T, Disconnect>) return "Disconnect";
            else return "unknown";
        },
        c);
}

/// @brief The node a command affects (if any). The undo stack coalesces per node with it.
[[nodiscard]] inline std::optional<NodeId> command_target(const Command& c) noexcept {
    return std::visit(
        [](const auto& v) -> std::optional<NodeId> {
            using T = std::decay_t<decltype(v)>;
            if constexpr (std::is_same_v<T, AddNode>) return v.id;
            else if constexpr (std::is_same_v<T, RemoveNode>) return v.id;
            else if constexpr (std::is_same_v<T, SetParam>) return v.id;
            else if constexpr (std::is_same_v<T, EraseParam>) return v.id;
            else if constexpr (std::is_same_v<T, SetNodeName>) return v.id;
            else if constexpr (std::is_same_v<T, SetBypass>) return v.id;
            else if constexpr (std::is_same_v<T, Connect>) return v.to.node;
            else if constexpr (std::is_same_v<T, Disconnect>) return v.input.node;
            else return std::nullopt;
        },
        c);
}

}  // namespace qp::graph
